name: python | validation

on:
  pull_request:

permissions:
  pull-requests: write
  contents: read

jobs:
  static-checks:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: python | setup 3.12
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: poetry | install
          run: |
            python -m pip install --upgrade pip
            pip install poetry

        - name: poetry | install dependencies
          run: poetry install --no-interaction

        - name: check | black check
          run: |
            poetry run black --check .

        - name: check | ruff
          run: |
            poetry run ruff check .

        - name: check | mypy
          run: |
            poetry run mypy .

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: python | setup  ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: poetry | install
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: poetry | install dependencies
        run: poetry install --no-interaction

      - name: tests | run
        run: |
          poetry run coverage run -m pytest tests/ -v
          poetry run coverage xml --omit "tests/**/*"
      
      - name: tests | coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: "coverage.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          # thresholds: "${{ inputs.low-pct-coverage-threshold }} ${{ inputs.high-pct-coverage-threshold }}"

      - name: coverage | add header
        run: |
          echo "## Coverage Report" > coverage.md
          cat code-coverage-results.md >> coverage.md
  
      - name: tests | pr-comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: ${{ github.event_name == 'pull_request'}}
        with:
          header: Coverage Report
          hide_and_recreate: true
          path: coverage.md